#AnalyzeSatMutv1.0 Data
analyze_satmut_data: ./data/counts/variant_counts.csv

#Computational Predictors
alphamissense: ./data/computational_predictors/SMARCB1_AlphaMissense_annotated.tsv
cadd: ./data/computational_predictors/SMARCB1_CADD_v1.7_annotated.tsv
revel: ./data/computational_predictors/SMARCB1_REVEL_v1.3_annotated.tsv 
