My main question: which genes bound by SWI/SNF are also transcriptionally responsive to SMARCB1


```{r}

library(readr)
library(dplyr)
library(readxl)
library(ggplot2)
library(ggrepel)


swisnf_gained <- read_tsv("./results/rna_atac_integration/annotated_significant_peaks/significant_gain_swisnf_annotated.bed")

I315IvI315X_rna <- read_xlsx("./results/rna_analysis/I315IvI315X_all_genes.xlsx")

names(I315IvI315X_rna)[names(I315IvI315X_rna) == "ENSEMBL"] <- "Gene Name"




I315IvI315X_merged_gain <- swisnf_gained %>%
  left_join(I315IvI315X_rna %>% dplyr::select(`Gene Name`, log2FoldChange, padj), by = "Gene Name")


I315IvI315X_rna_atac_merged_gain <- I315IvI315X_merged_gain %>%
  left_join(I315IvI315X_rna %>% dplyr::select('Gene Name', log2FoldChange, padj), by = "Gene Name")

names(I315IvI315X_rna_atac_merged_gain)[names(I315IvI315X_rna_atac_merged_gain) == "padj"] <- "FDR_RNA"

names(I315IvI315X_rna_atac_merged_gain)[names(I315IvI315X_rna_atac_merged_gain) == "FDR"] <- "FDR_ATAC"

names(I315IvI315X_rna_atac_merged_gain)[names(I315IvI315X_rna_atac_merged_gain) == "Fold"] <- "LFC_ATAC"

names(I315IvI315X_rna_atac_merged_gain)[names(I315IvI315X_rna_atac_merged_gain) == "log2FoldChange"] <- "LFC_RNA"






swisnf_lost <- read_tsv("./results/rna_atac_integration/annotated_significant_peaks/significant_loss_swisnf_annotated.bed")
```




```{r}

res_df_i315i <- I315IvI315X_rna %>%
  mutate(Significance = case_when(
    padj <= 0.05 & 
    log2FoldChange > 1 ~ "up",
    padj <= 0.05 & 
    log2FoldChange < -1 ~ "down",
    TRUE ~ "nonsig"
  ))

res_df_i315i$Significance <- factor(res_df_i315i$Significance, levels = c("nonsig","up", "down"))
res_df_i315i <- res_df_i315i[order(res_df_i315i$Significance), ]

g3 <- res_df_i315i %>%
  filter(res_df_i315i$'Gene Name' == "ARHGAP40" |
         res_df_i315i$'Gene Name' == "ARHGDIB" |
         res_df_i315i$'Gene Name' == "ARHGEF3" |
         res_df_i315i$'Gene Name' == "RHOU")

g_highlight <- res_df_i315i %>%
  filter(`Gene Name` %in% I315IvI315X_merged_gain$`Gene Name`)

g_highlight_sig <- g_highlight %>%
  filter(Significance %in% c("up", "down"))


plot_I315IvI315X <- ggplot(data = res_df_i315i, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = Significance), size = 2) +
  geom_point(data = g3, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  # Overlay circles for your highlight list
  geom_point(data = g_highlight_sig, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  theme_bw() +
  ylim(0, 200) +
  xlim(-12,12) +
  labs(title = "SMARCB1 I315I vs I315*", x = "log2FoldChange", y = "-log10(padj)") +
  geom_text_repel(data = g3, label = g3$'Gene Name', hjust = 1.3, vjust = -3, size = 5) +
  theme(text = element_text(family = "Arial", size = 15),
        axis.text = element_text(size = 15),
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_color_manual(values = c("#CCCDCD", "#6495ED", "#F32316")) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  ) +
  geom_vline(xintercept = 1, linetype = "dotted", size = 0.4) +
  geom_vline(xintercept = -1, linetype = "dotted", size = 0.4) +
  geom_hline(yintercept = 1.30102999566, linetype = "dotted", size = 0.4) +
  theme(legend.position = "none")

plot_I315IvI315X

```


```{r}


WTvW281X_rna <- read_xlsx("./results/rna_analysis/WTvW281X_all_genes.xlsx")

names(WTvW281X_rna)[names(WTvW281X_rna) == "ENSEMBL"] <- "Gene Name"


WTvW281X_merged_gain <- swisnf_gained %>%
  left_join(WTvW281X_rna %>% dplyr::select(`Gene Name`, log2FoldChange, padj), by = 'Gene Name')


res_df_WT <- WTvW281X_rna %>%
  mutate(Significance = case_when(
    padj <= 0.05 & 
    log2FoldChange > 1 ~ "up",
    padj <= 0.05 & 
    log2FoldChange < -1 ~ "down",
    TRUE ~ "nonsig"
  ))

res_df_WT$Significance <- factor(res_df_WT$Significance, levels = c("nonsig","up", "down"))
res_df_WT <- res_df_WT[order(res_df_WT$Significance), ]

g1 <- res_df_WT %>%
  filter(res_df_WT$'Gene Name' == "ARHGAP40" |
         res_df_WT$'Gene Name' == "ARHGDIB" |
         res_df_WT$'Gene Name' == "ARHGEF3" |
         res_df_WT$'Gene Name' == "RHOU")


g_highlight2 <- res_df_WT %>%
  filter(`Gene Name` %in% WTvW281X_merged_gain$"Gene Name")

g_highlight_sig2 <- g_highlight2 %>%
  filter(Significance %in% c("up", "down"))


plot_WTvW281X <- ggplot(data = res_df_WT, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = Significance), size = 2) +
  geom_point(data = g1, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  geom_point(data = g_highlight_sig2, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  theme_bw() +
  ylim(0, 210) +
  xlim(-12,12) +
  labs(title = "SMARCB1 WT vs W281*", x = "log2FoldChange", y = "-log10(padj)") +
  geom_text_repel(data = g1, label = g1$'Gene Name', hjust = 1.3, vjust = -3, size = 5) +
  theme(text = element_text(family = "Arial", size = 15),
        axis.text = element_text(size = 15),
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_color_manual(values = c("#CCCDCD", "#6495ED", "#F32316")) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  ) +
  geom_vline(xintercept = 1, linetype = "dotted", size = 0.4) +
  geom_vline(xintercept = -1, linetype = "dotted", size = 0.4) +
  geom_hline(yintercept = 1.30102999566, linetype = "dotted", size = 0.4) +
  theme(legend.position = "none")

plot_WTvW281X


```



```{r}
overlap_genes <- intersect(g_highlight_sig$`Gene Name`,
                           g_highlight_sig2$`Gene Name`)
```









```{r}
library(clusterProfiler)
library(org.Hs.eg.db)

genes <- unique(overlap_genes)

gene_entrez <- bitr(genes, fromType = "SYMBOL", 
                    toType = "ENTREZID", 
                    OrgDb = org.Hs.eg.db)

# Use only the Entrez IDs
entrez_ids <- gene_entrez$ENTREZID

ego <- enrichGO(gene         = entrez_ids,
                OrgDb        = org.Hs.eg.db,
                keyType      = "ENTREZID",
                ont          = "BP",        # Biological Process, can also use "MF" or "CC"
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.2,
                readable     = TRUE)        # convert back to gene symbols

barplot(ego, showCategory = 30)       # top 20 GO terms
dotplot(ego, showCategory = 15)


head(ego, n=20)         # Top enriched GO terms
summary(ego) 


```



```{r}
# Identify vascular/circulatory terms to exclude
vascular_terms <- c("vascular", "circulatory", "blood vessel", "tube diameter", "tube size")

# Create a pattern to match any of these terms
vascular_pattern <- paste(vascular_terms, collapse = "|")

# Filter out terms that match the pattern
keep_indices <- which(!grepl(vascular_pattern, ego@result$Description, ignore.case = TRUE))

filtered_ego <- ego
filtered_ego@result <- ego@result[keep_indices, ]

dotplot(filtered_ego)
```



```{r}

df <- filtered_ego@result

df$neg_log_padj <- -log10(df$p.adjust)
# Get top 10 by p.adjust (most significant)
df <- df[order(df$p.adjust), ][1:10, ]

# Calculate numeric gene ratio and -log10(p.adjust)
df$GeneRatio_numeric <- sapply(strsplit(as.character(df$GeneRatio), "/"), 
                               function(x) as.numeric(x[1])/as.numeric(x[2]))
df$neg_log_p <- -log10(df$p.adjust)

# Create the plot
p <- ggplot(df, aes(x = neg_log_p, y = reorder(Description, neg_log_p))) +
  geom_col(aes(fill = GeneRatio_numeric), width = 0.7, color = "black", linewidth = 0.3) +
  scale_fill_gradient(low = "#FDD49E", high = "#B85450", name = "Gene Ratio") +
  labs(x = "-log10(p.adjust)", y = NULL) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 10, color = "black"),
    axis.text.x = element_text(size = 10, color = "black"),
    axis.title.x = element_text(size = 12),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  expand_limits(x = 0)

p

write_tsv(df, "./results/GO_analysis/WT_v_nonsense_GO_terms.tsv")


ggsave("./plots/GO_analysis/go_dotplot_WT_v_nonsense.svg", plot = p, width = 8, height = 6)

```


Cite this: 

RhoA-dependent regulation of cell migration by the tumor suppressor INI1 https://pubmed.ncbi.nlm.nih.gov/18676838/

https://pmc.ncbi.nlm.nih.gov/articles/PMC2709499/

https://pubmed.ncbi.nlm.nih.gov/15150092/





============= WT vs missense mutant Analysis ==================

```{r}

I315IvI315R_rna <- read_xlsx("./results/rna_analysis/I315IvI315R_all_genes.xlsx")


names(I315IvI315R_rna)[names(I315IvI315R_rna) == "ENSEMBL"] <- "Gene Name"

I315IvI315R_merged_gain <- swisnf_gained %>%
  left_join(I315IvI315R_rna %>% dplyr::select(`Gene Name`, log2FoldChange, padj), by = 'Gene Name')

res_df_I315IvI315R <- I315IvI315R_rna %>%
  mutate(Significance = case_when(
    padj <= 0.05 & 
    log2FoldChange > 1 ~ "up",
    padj <= 0.05 & 
    log2FoldChange < -1 ~ "down",
    TRUE ~ "nonsig"
  ))

res_df_I315IvI315R$Significance <- factor(res_df_I315IvI315R$Significance, levels = c("nonsig","up", "down"))
res_df_I315IvI315R <- res_df_I315IvI315R[order(res_df_I315IvI315R$Significance), ]

g1 <- res_df_I315IvI315R %>%
  filter(res_df_I315IvI315R$'Gene Name' == "SMARCB1")

g1 <- res_df_I315IvI315R %>%
  filter(res_df_I315IvI315R$'Gene Name' == "ARHGAP40" |
         res_df_I315IvI315R$'Gene Name' == "ARHGDIB" |
         res_df_I315IvI315R$'Gene Name' == "ARHGEF3" |
         res_df_I315IvI315R$'Gene Name' == "RHOU")


g_highlight3 <- res_df_I315IvI315R %>%
  filter(`Gene Name` %in% I315IvI315R_merged_gain$"Gene Name")

g_highlight_sig3 <- g_highlight3 %>%
  filter(Significance %in% c("up", "down"))

plot_I315IvI315R <- ggplot(data = res_df_I315IvI315R, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = Significance), size = 2) +
  geom_point(data = g_highlight_sig3, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  geom_point(data = g1, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  theme_bw() +
  ylim(0, 210) +
  xlim(-10,10) +
  labs(title = "SMARCB1 I315I vs I315R", x = "log2FoldChange", y = "-log10(padj)") +
  geom_text_repel(data = g1, label = g1$'Gene Name', hjust = 1.3, vjust = -3, size = 5) +
  theme(text = element_text(family = "Arial", size = 15),
        axis.text = element_text(size = 15),
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_color_manual(values = c("#CCCDCD", "#6495ED", "#F32316")) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  ) +
  geom_vline(xintercept = 1, linetype = "dotted", size = 0.4) +
  geom_vline(xintercept = -1, linetype = "dotted", size = 0.4) +
  geom_hline(yintercept = 1.30102999566, linetype = "dotted", size = 0.4) +
  theme(legend.position = "none")

plot_I315IvI315R

```


```{r}

WTvW281P_rna <- read_xlsx("./results/rna_analysis/WTvW281P_all_genes.xlsx")


names(WTvW281P_rna)[names(WTvW281P_rna) == "ENSEMBL"] <- "Gene Name"

WTvW281P_merged_gain <- swisnf_gained %>%
  left_join(WTvW281P_rna %>% dplyr::select(`Gene Name`, log2FoldChange, padj), by = 'Gene Name')

res_df_WTvW281P <- WTvW281P_rna %>%
  mutate(Significance = case_when(
    padj <= 0.05 & 
    log2FoldChange > 1 ~ "up",
    padj <= 0.05 & 
    log2FoldChange < -1 ~ "down",
    TRUE ~ "nonsig"
  ))

res_df_WTvW281P$Significance <- factor(res_df_WTvW281P$Significance, levels = c("nonsig","up", "down"))
res_df_WTvW281P <- res_df_WTvW281P[order(res_df_WTvW281P$Significance), ]

g1 <- res_df_WTvW281P %>%
  filter(res_df_WTvW281P$'Gene Name' == "SMARCB1")

g1 <- res_df_WTvW281P %>%
  filter(res_df_WTvW281P$'Gene Name' == "ARHGAP40" |
         res_df_WTvW281P$'Gene Name' == "ARHGDIB" |
         res_df_WTvW281P$'Gene Name' == "ARHGEF3" |
         res_df_WTvW281P$'Gene Name' == "RHOU")


g_highlight4 <- res_df_WTvW281P %>%
  filter(`Gene Name` %in% WTvW281P_merged_gain$"Gene Name")

g_highlight_sig4 <- g_highlight4 %>%
  filter(Significance %in% c("up", "down"))

plot_WTvW281P <- ggplot(data = res_df_WTvW281P, aes(x = log2FoldChange, y = -log10(padj))) +
  geom_point(aes(color = Significance), size = 2) +
  geom_point(data = g1, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  geom_point(data = g_highlight_sig4, aes(x = log2FoldChange, y = -log10(padj)), 
             color = "black", size = 2, shape = 1) +
  theme_bw() +
  ylim(0, 210) +
  xlim(-10,10) +
  labs(title = "SMARCB1 WT vs W281P", x = "log2FoldChange", y = "-log10(padj)") +
  geom_text_repel(data = g1, label = g1$'Gene Name', hjust = 1.3, vjust = -3, size = 5) +
  theme(text = element_text(family = "Arial", size = 15),
        axis.text = element_text(size = 15),
        plot.title = element_text(size = 15, hjust = 0.5)) +
  scale_color_manual(values = c("#CCCDCD", "#6495ED", "#F32316")) +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    panel.border = element_rect(colour = "black", fill = NA, size = 1)
  ) +
  geom_vline(xintercept = 1, linetype = "dotted", size = 0.4) +
  geom_vline(xintercept = -1, linetype = "dotted", size = 0.4) +
  geom_hline(yintercept = 1.30102999566, linetype = "dotted", size = 0.4) +
  theme(legend.position = "none")

plot_WTvW281P

```


```{r}
overlap_genes2 <- intersect(g_highlight_sig3$`Gene Name`,
                           g_highlight_sig4$`Gene Name`)
```


```{r}

library(clusterProfiler)
library(org.Hs.eg.db)

genes2 <- unique(overlap_genes2)

gene_entrez <- bitr(genes2, fromType = "SYMBOL", 
                    toType = "ENTREZID", 
                    OrgDb = org.Hs.eg.db)

# Use only the Entrez IDs
entrez_ids <- gene_entrez$ENTREZID

ego <- enrichGO(gene         = entrez_ids,
                OrgDb        = org.Hs.eg.db,
                keyType      = "ENTREZID",
                ont          = "BP",        # Biological Process, can also use "MF" or "CC"
                pAdjustMethod = "BH",
                pvalueCutoff = 0.05,
                qvalueCutoff = 0.2,
                readable     = TRUE)        # convert back to gene symbols

barplot(ego, showCategory = 30)       # top 20 GO terms
dotplot(ego, showCategory = 15)

#ggsave("./plots/GO_analysis/go_dotplot_WT_v_missense.svg", plot = p, width = 8, height = 6)

head(ego, n=20)         # Top enriched GO terms
summary(ego) 

```

```{r}
# Identify vascular/circulatory terms to exclude
vascular_terms <- c("vascular", "circulatory", "blood vessel", "tube diameter", "tube size")

# Create a pattern to match any of these terms
vascular_pattern <- paste(vascular_terms, collapse = "|")

# Filter out terms that match the pattern
keep_indices <- which(!grepl(vascular_pattern, ego@result$Description, ignore.case = TRUE))

filtered_ego <- ego
filtered_ego@result <- ego@result[keep_indices, ]

dotplot(filtered_ego)
```

```{r}


df <- filtered_ego@result

df$neg_log_padj <- -log10(df$p.adjust)
# Get top 10 by p.adjust (most significant)
df <- df[order(df$p.adjust), ][1:10, ]

# Calculate numeric gene ratio and -log10(p.adjust)
df$GeneRatio_numeric <- sapply(strsplit(as.character(df$GeneRatio), "/"), 
                               function(x) as.numeric(x[1])/as.numeric(x[2]))
df$neg_log_p <- -log10(df$p.adjust)

# Create the plot
p <- ggplot(df, aes(x = neg_log_p, y = reorder(Description, neg_log_p))) +
  geom_col(aes(fill = GeneRatio_numeric), width = 0.7, color = "black", linewidth = 0.3) +
  scale_fill_gradient(low = "#FDD49E", high = "#B85450", name = "Gene Ratio") +
  labs(x = "-log10(p.adjust)", y = NULL) +
  theme_minimal() +
  theme(
    axis.text.y = element_text(size = 10, color = "black"),
    axis.text.x = element_text(size = 10, color = "black"),
    axis.title.x = element_text(size = 12),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank()
  ) +
  expand_limits(x = 0)

write_tsv(df, "./results/GO_analysis/WT_v_missense_GO_terms.tsv")


ggsave("./plots/GO_analysis/go_dotplot_WT_v_missense.svg", plot = p, width = 8, height = 6)

```













