---
title: "MITEseq Analysis Pipeline"
author: "Garrett Cooper"
date: 1/19/2024
output:
  github_document:
    toc: true
    html_preview: false
editor_options: 
  chunk_output_type: inline
---



```{r}

library(readr)
library(dplyr)
library(yaml)
library(stringr)
library(tidyr)

#read in config file
config <- read_yaml("./config.yaml")

#We are filtering data that was obtained from from AACR Genie v16.1

missense_count_by_mutation_genie <- read_tsv(file=config$genie_smarcb1_missense_mutation_freq)

cadd_data_exons_missense <- read_tsv(file=config$cadd_missense)

```





```{r}

tiff("./plots/patient_data/Genie_v_CADD.tiff", units="in", width=5, height=5, res=300)

colnames(missense_count_by_mutation_genie)[colnames(missense_count_by_mutation_genie) == "genie_missense$`Protein Change`"] <- "Protein_Change"

merged_dataframe <- left_join(missense_count_by_mutation_genie, cadd_data_exons_missense, by = c("Protein_Change" = "AA_Substitution"))

y <- merged_dataframe$total_count; x <- merged_dataframe$PHRED

r_squared <- cor(x, y, use = "complete.obs")^2

plot(x, y, pch=16, xlab="PHRED", ylab="Mutation Count (Genie)",
     main=paste("PHRED vs Patient Data\nR^2 =", round(r_squared, 2)), cex=0.5)

dev.off()


cadd_pathogenic <- cadd_data_exons_missense %>%
  filter(cadd_data_exons_missense$PHRED > 20)

merged_dataframe_pathogenic <- left_join(missense_count_by_mutation_genie, cadd_data_exons_missense, by = c("Protein_Change" = "AA_Substitution"))


```


```{r}

missense_count_by_mutation_genie <- read_tsv(file=config$genie_smarcb1_missense_mutation_freq)

revel_data_exons_missense <- read_tsv(file=config$revel_duplicate_avg)

```




```{r}

tiff("./plots/patient_data/Genie_v_REVEL.tiff", units="in", width=5, height=5, res=300)

colnames(missense_count_by_mutation_genie)[colnames(missense_count_by_mutation_genie) == "genie_missense$`Protein Change`"] <- "AA_Substitution"

merged_dataframe <- left_join(missense_count_by_mutation_genie, revel_data_exons_missense, by = c("AA_Substitution" = "AA_Substitution"))

y <- merged_dataframe$total_count; x <- merged_dataframe$REVEL

r_squared <- cor(x, y, use = "complete.obs")^2

plot(x, y, pch=16, xlab="REVEL", ylab="Mutation Count (Genie)",
     main=paste("REVEL vs Patient Data\nR^2 =", round(r_squared, 2)), cex=0.5)

dev.off()


```


```{r}
alphamissense_missense <- read_tsv(file=config$alphamissense)
```


```{r}

tiff("./plots/patient_data/Genie_v_AlphaMissense.tiff", units="in", width=5, height=5, res=300)

colnames(missense_count_by_mutation_genie)[colnames(missense_count_by_mutation_genie) == "genie_missense$`Protein Change`"] <- "AA_Substitution"

merged_dataframe <- left_join(missense_count_by_mutation_genie, alphamissense_missense, by = c("AA_Substitution" = "protein_variant"))

y <- merged_dataframe$total_count; x <- merged_dataframe$am_pathogenicity

r_squared <- cor(x, y, use = "complete.obs")^2

plot(x, y, pch=16, xlab="AlphaMissense", ylab="Mutation Count (Genie)",
     main=paste("AlphaMissense vs Patient Data\nR^2 =", round(r_squared, 2)), cex=0.5)

dev.off()



```

```{r}

mite_data <- read.csv(file=config$mitedata)


colnames(mite_data)[colnames(mite_data) == "Substitution"] <- "Protein_Change"

colnames(missense_count_by_mutation_genie)[colnames(missense_count_by_mutation_genie) == "AA_Substitution"] <- "Protein_Change"

merged_dataframe <- left_join(missense_count_by_mutation_genie, mite_data, by = c("Protein_Change" = "Protein_Change"))


library(ggplot2)
library(ggrepel)

# Ensure x and y are defined in your environment if you're referencing them in the title
x <- merged_dataframe$all_reps_zscore
y <- merged_dataframe$total_count

# Labeling condition
merged_dataframe$label <- ifelse(
  merged_dataframe$total_count > 15 | merged_dataframe$all_reps_zscore > 2,
  merged_dataframe$Protein_Change,
  NA
)

r_squared <- round(cor(merged_dataframe$all_reps_zscore, merged_dataframe$total_count, use = "complete.obs")^2, 2)

ggplot(merged_dataframe, aes(x = all_reps_zscore, y = total_count)) +
  geom_point(size = 1) +
  geom_text_repel(
    aes(label = label),
    size = 4,
    max.overlaps = Inf,
    segment.color = "gray30",
    segment.size = 0.3,
    box.padding = 0.4,
    point.padding = 0.3,
    min.segment.length = 0,
    direction = "y",
    nudge_y = 2,
    nudge_x = 0.2
  ) +
  annotate("text", x = Inf, y = Inf, 
           label = paste("R² =", r_squared), 
           hjust = 4, vjust = 2, size = 8, color = "black") +  # Increased from 5 to 8
  labs(
    x = "DMS z-score", 
    y = "Mutation Count (Genie)"
  ) +
  theme_classic() +
  theme(
    panel.grid = element_blank(),
    legend.text = element_text(size = 20),
    axis.title = element_text(size = 20),        # Axis label size
    axis.text = element_text(size = 16)          # Axis tick label size
  )

ggsave("./plots/patient_data/Genie_v_DMS.tiff", device = "tiff", width = 8, height = 6, dpi = 300)


```


