---
title: "ROC Curve Analysis"
author: "Garrett Cooper"
date: 11/23/2024
output:
  github_document:
    toc: true
    html_preview: false
editor_options: 
  chunk_output_type: inline
---

```{r}

library(readr)
library(dplyr)
library(yaml)

#read in config file
config <- read_yaml("./config.yaml")

```

Read in all of the data sources
```{r}

clinvar_SMARCB1 <- read_tsv(file=config$clinvar)

revel_SMARCB1 <- read_tsv(file=config$revel_duplicate_avg)

cadd_SMARCB1 <- read_tsv(file=config$cadd_duplicate_avg)

alpha_SMARCB1 <- read_tsv(file=config$alphamissense)

mite_data <- read.csv(file=config$mitedata)

```


Integrate them all into one dataframe
```{r}
#There are multiple nucleotide substitutions that lead to the same amino acid change (or silent change). We double checked these duplicates are classified the same. Here we keep only the first instance to not add unnecessary data.

clinvar_SMARCB1_no_duplicates <- clinvar_SMARCB1 %>%
  distinct(`Protein change`, .keep_all = TRUE)


integrated_data <- mite_data %>%
  left_join(clinvar_SMARCB1_no_duplicates %>% select("Protein change", "Germline classification", "Condition(s)"), 
            by = c("Substitution" = "Protein change" ))



integrated_data <- integrated_data %>%
  left_join(revel_SMARCB1 %>% select("AA_Substitution", "REVEL"),
            by = c("Substitution" = "AA_Substitution"))



integrated_data <- integrated_data %>%
  left_join(cadd_SMARCB1 %>% select("AA_Substitution", "PHRED"),
            by = c("Substitution" = "AA_Substitution"))


#Integrate alphamissense data
integrated_data <- integrated_data %>%
  left_join(alpha_SMARCB1 %>% select("protein_variant", "am_pathogenicity"),
            by = c("Substitution" = "protein_variant"))



write_tsv(integrated_data, "./results/ROC_curve_analysis/integrated_data_DMS_ClinVar_REVEL_CADD.tsv")


```


Plot ROC Curves for all data in ClinVar
```{r}

library(pROC)

clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic', 'Likely pathogenic')


integrated_data$response <- ifelse(integrated_data$'Germline classification' %in% clinvar_pos, 1, 0)

roc_cadd <- roc(integrated_data$response, integrated_data$PHRED)

roc_zscore <- roc(integrated_data$response, integrated_data$all_reps_zscore)


tiff("./plots/ROC_curves/ROC_CADD_DMS.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue",lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"))
legend("bottomright", legend = legend_text, col = c("red", "lightblue"), lwd = 4,cex=1.25)

dev.off()

tiff("./plots/ROC_curves/ROC_DMS_only.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"))
legend("bottomright", legend = legend_text, col = c("red"), lwd = 4,cex=1.25)

dev.off()


clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic')


integrated_data$response <- ifelse(integrated_data$'Germline classification' %in% clinvar_pos, 1, 0)

roc_cadd <- roc(integrated_data$response, integrated_data$PHRED)

roc_zscore <- roc(integrated_data$response, integrated_data$all_reps_zscore)


tiff("./plots/ROC_curves/ROC_CADD_DMS_stringent.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue",lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"))
legend("bottomright", legend = legend_text, col = c("red", "lightblue"), lwd = 4,cex=1.25)

dev.off()

tiff("./plots/ROC_curves/ROC_DMS_only_stringent.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"))
legend("bottomright", legend = legend_text, col = c("red"), lwd = 4,cex=1.25)

dev.off()


```

Plot ROC Curves for just missense data
```{r}

library(pROC)

integrated_data_missense_only <- integrated_data %>%
  filter(integrated_data$Mutation_Type == "M")

clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic', 'Likely pathogenic')


integrated_data_missense_only$response <- ifelse(integrated_data_missense_only$'Germline classification' %in% clinvar_pos, 1, 0)

roc_cadd <- roc(integrated_data_missense_only$response, integrated_data_missense_only$PHRED)

roc_revel <- roc(integrated_data_missense_only$response, integrated_data_missense_only$REVEL)

roc_zscore <- roc(integrated_data_missense_only$response, integrated_data_missense_only$all_reps_zscore)

roc_am <- roc(integrated_data_missense_only$response, integrated_data_missense_only$am_pathogenicity)




tiff("./plots/ROC_curves/ROC_missense_only.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue",lwd=4, add = TRUE)
plot(roc_revel, col = "gainsboro",lwd=4, add = TRUE)
plot(roc_am, col = "black",lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"),
                 paste0("Revel (AUC=", round(auc(roc_revel), 2), ")"),
                 paste0("AlphaMissense (AUC=", round(auc(roc_am), 2), ")"))

legend("bottomright", legend = legend_text, col = c("red", "lightblue", "gainsboro", "black"), lwd = 4,cex=1.25)

dev.off()


```





```{r}

tiff("./plots/computational_correlations/AlphaMissense_v_DMS.tiff", units="cm", width=30, height=14, res=300)

y <- integrated_data$all_reps_zscore; x <- integrated_data$am_pathogenicity

plot(x,y,pch=16,xlab="AlphaMissense",ylab="Average Z-Score",main=paste("AlphaMissense v DMS"), cex=0.5, xlim=c(0,1), ylim=c(-5,5))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared
# Add the slope and R^2 value as text on the plot
text(0.1, 4, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)

dev.off()


tiff("./plots/computational_correlations/REVEL_v_DMS.tiff", units="cm", width=30, height=14, res=300)

y <- integrated_data$all_reps_zscore; x <- integrated_data$REVEL

plot(x,y,pch=16,xlab="REVEL",ylab="Average Z-Score",main=paste("REVEL v DMS"), cex=0.5, xlim=c(0,1), ylim=c(-5,5))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared

# Add the slope and R^2 value as text on the plot
text(0.1, 3, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)

dev.off()


tiff("./plots/computational_correlations/CADD_v_DMS_NMS.tiff", units="in", width=12, height=7, res=300)

integrated_data_NMS <- integrated_data %>%
  filter(integrated_data$Mutation_Type == "S" | integrated_data$Mutation_Type == "N" | integrated_data$Mutation_Type == "M")


y <- integrated_data_NMS$all_reps_zscore; x <- integrated_data_NMS$PHRED; z <- as.factor(integrated_data_NMS$Mutation_Type)

plot(x, y, pch = 16, col = c("gray70", "red", "black")[z], 
     xlab = "CADD", ylab = "Z-Score", 
     main = paste("CADD v DMS"), cex = 1.5, 
     xlim = c(0, 60), ylim = c(-6.5, 6.5), 
     cex.lab = 2, cex.axis = 2)

par(new = TRUE)  # Ensures that plot remains active
box(bty = "l")  # Removes top and right spines, keeps bottom and left


dev.off()



tiff("./plots/computational_correlations/CADD_v_DMS_NS.tiff", units="cm", width=30, height=14, res=300)

integrated_data_NS <- integrated_data %>%
  filter(integrated_data$Mutation_Type == "S" | integrated_data$Mutation_Type == "N")


y <- integrated_data_NS$all_reps_zscore; x <- integrated_data_NS$PHRED; z <- as.factor(integrated_data_NS$Mutation_Type)

plot(x,y,pch=16,col=c("blue", "red", "gray")[z], xlab="CADD",ylab="Z-Score",main=paste("CADD v DMS"), cex=0.5, xlim=c(0,60), ylim=c(-6.5,6.5))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared

# Add the slope and R^2 value as text on the plot
text(5, 3, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)


dev.off()


```


```{r}

y <- integrated_data$REVEL; x <- integrated_data$am_pathogenicity

plot(x,y,pch=16,xlab="AlphaMissense",ylab="REVEL",main=paste("All reps by amino acid silent and Missense"), cex=0.5, xlim=c(0,1), ylim=c(0,1))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared

# Add the slope and R^2 value as text on the plot
text(0.5, 0.1, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)




y <- integrated_data$REVEL; x <- integrated_data$PHRED

plot(x,y,pch=16,xlab="CADD",ylab="REVEL",main=paste("All reps by amino acid silent and Missense"), cex=0.5, xlim=c(0,40), ylim=c(0,1))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared

# Add the slope and R^2 value as text on the plot
text(30, 0.1, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)


y <- integrated_data$am_pathogenicity; x <- integrated_data$PHRED

plot(x,y,pch=16,xlab="CADD",ylab="AlphaMissense",main=paste("All reps by amino acid silent and Missense"), cex=0.5, xlim=c(0,40), ylim=c(0,1))

fit1 <- lm(y ~ x)
abline(fit1, col="red", lwd=2)  # Red line for the best fit

r_squared1 <- summary(fit1)$r.squared

# Add the slope and R^2 value as text on the plot
text(5, 0.5, paste("\nR^2: ", round(r_squared1, 3)), col="red", cex=1)




```





Precision Recall Curves

```{r}

library(precrec)


response <- integrated_data_missense_only$response
predictors <- integrated_data_missense_only[,c(12,19,20,21)]

# Create PR curves for all predictors
prc_results <- evalmod(scores = predictors, labels = response)

# Plot Precision-Recall curves
plot(prc_results)


prc_results_DMS <- evalmod(scores = predictors$all_reps_zscore, labels = response)
plot(prc_results_DMS)




```



```{r}

library(pROC)

integrated_data_missense_only <- integrated_data %>%
  filter(integrated_data$Mutation_Type == "M")

clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic', 'Likely pathogenic')

condition <- c('Hereditary cancer-predisposing syndrome|not provided')


integrated_data_missense_only$response <- ifelse(integrated_data_missense_only$'Germline classification' %in% clinvar_pos & integrated_data_missense_only$`Condition(s)` %in% condition, 1, 0)

roc_cadd <- roc(integrated_data_missense_only$response, integrated_data_missense_only$PHRED)

roc_revel <- roc(integrated_data_missense_only$response, integrated_data_missense_only$REVEL)

roc_zscore <- roc(integrated_data_missense_only$response, integrated_data_missense_only$all_reps_zscore)

roc_am <- roc(integrated_data_missense_only$response, integrated_data_missense_only$am_pathogenicity)




tiff("./plots/ROC_curves/ROC_missense_only_cancer_variants_only.tiff", units="in", width=6, height=6, res=600)

plot(roc_zscore, col = "red",lwd=4, xlab = "Specificity", ylab = "Sensitivity",cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue",lwd=4, add = TRUE)
plot(roc_revel, col = "gainsboro",lwd=4, add = TRUE)
plot(roc_am, col = "black",lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"),
                 paste0("REVEL (AUC=", round(auc(roc_revel), 2), ")"),
                 paste0("AlphaMissense (AUC=", round(auc(roc_am), 2), ")"))

legend("bottomright", legend = legend_text, col = c("red", "lightblue", "gainsboro", "black"), lwd = 4,cex=1.25)

dev.off()


ROC_supp_data <- integrated_data_missense_only[,c(1,3,4,5,17,18,19,20,21,12,22)]

write_tsv(ROC_supp_data, "./results/ROC_curve_analysis/ROC_supp_data.tsv")


```



```{r}

gnomAD_missense <- read_tsv("~/Library/CloudStorage/GoogleDrive-gcooper.gene@gmail.com/.shortcut-targets-by-id/1rALxO157_wDKXF4JjmT8CFruCpBbWa5o/Hong Lab Project Folders/Results GC/17-SMARCB1_MITEseq2/Manuscript/SMARCB1_DMS/data/gnomADv4.1.0/gnomad_missense_mutants.tsv")

# Create amino acid conversion table
aa_convert <- c(
  'Ala' = 'A', 'Arg' = 'R', 'Asn' = 'N', 'Asp' = 'D',
  'Cys' = 'C', 'Gln' = 'Q', 'Glu' = 'E', 'Gly' = 'G',
  'His' = 'H', 'Ile' = 'I', 'Leu' = 'L', 'Lys' = 'K',
  'Met' = 'M', 'Phe' = 'F', 'Pro' = 'P', 'Ser' = 'S',
  'Thr' = 'T', 'Trp' = 'W', 'Tyr' = 'Y', 'Val' = 'V',
  'Ter' = '*', 'Sec' = 'U', 'Pyl' = 'O'
)

# Function to convert protein consequence format
convert_protein_consequence <- function(protein_conseq) {
  # Remove "p." prefix
  conseq <- gsub("^p\\.", "", protein_conseq)
  
  # Extract reference AA (3-letter), position, and alternate AA (3-letter)
  # Pattern: 3 letters, then numbers, then 3 letters
  ref_aa <- substr(conseq, 1, 3)
  alt_aa <- substr(conseq, nchar(conseq)-2, nchar(conseq))
  position <- gsub("[A-Za-z]", "", conseq)
  
  # Convert to 1-letter code
  ref_1letter <- aa_convert[ref_aa]
  alt_1letter <- aa_convert[alt_aa]
  
  # Combine
  result <- paste0(ref_1letter, position, alt_1letter)
  
  return(result)
}

# Apply to gnomAD dataframe
gnomAD_missense <- gnomAD_missense %>%
  mutate(Protein.Consequence.Short = sapply(Protein.Consequence, convert_protein_consequence))


```


GnomAD variants as negative

```{r}
library(pROC)
library(dplyr)

# Filter for missense mutations
integrated_data_missense_only <- integrated_data %>%
  filter(Mutation_Type == "M")


integrated_data_missense_only <- integrated_data_missense_only %>%
  left_join(
    gnomAD_missense %>% select(Protein.Consequence.Short, Allele.Frequency),
    by = c("Substitution" = "Protein.Consequence.Short")
  )


# Define positive cases
clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic', 'Likely pathogenic')
condition <- c('Hereditary cancer-predisposing syndrome|not provided')

# Create response variable:
# 1 = Pathogenic cancer variants
# 0 = Observed in gnomAD (but not pathogenic cancer variants)
# NA = everything else (excluded)
# Create response variable with pathogenic cancer variants taking priority
integrated_data_missense_only <- integrated_data_missense_only %>%
  mutate(response = case_when(
    # FIRST: Positive cases (checked first, so these take priority)
    `Germline classification` %in% clinvar_pos & `Condition(s)` %in% condition ~ 1,
    # SECOND: Negative controls (any variant with gnomAD data that wasn't already classified as positive)
    !is.na(Allele.Frequency) ~ 0,
    # Everything else excluded
    TRUE ~ NA_real_
  ))

# Filter to only variants with defined response
roc_data <- integrated_data_missense_only %>%
  filter(!is.na(response))

# Check class distribution
cat("Class distribution:\n")
table(roc_data$response)
cat("\nPositives:", sum(roc_data$response == 1), 
    "\nNegatives:", sum(roc_data$response == 0), "\n")

# Create ROC curves
roc_cadd <- roc(roc_data$response, roc_data$PHRED)
roc_revel <- roc(roc_data$response, roc_data$REVEL)
roc_zscore <- roc(roc_data$response, roc_data$all_reps_zscore)
roc_am <- roc(roc_data$response, roc_data$am_pathogenicity)

# Plot
tiff("./plots/ROC_curves/ROC_missense_cancer_vs_gnomad.tiff", 
     units="in", width=6, height=6, res=600)
plot(roc_zscore, col = "red", lwd=4, xlab = "Specificity", ylab = "Sensitivity",
     cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue", lwd=4, add = TRUE)
plot(roc_revel, col = "gainsboro", lwd=4, add = TRUE)
plot(roc_am, col = "black", lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"),
                 paste0("REVEL (AUC=", round(auc(roc_revel), 2), ")"),
                 paste0("AlphaMissense (AUC=", round(auc(roc_am), 2), ")"))
legend("bottomright", legend = legend_text, 
       col = c("red", "lightblue", "gainsboro", "black"), lwd = 4, cex=1.25)
dev.off()

# Save supplementary data
ROC_supp_data <- roc_data[,c(1,3,4,5,17,18,19,20,21,12,22)]
write_tsv(ROC_supp_data, "./results/ROC_curve_analysis/ROC_supp_data_gnomad_negatives.tsv")


```

gnomAD and ClinVar benign at negative

```{r}

library(pROC)
library(dplyr)

# Filter for missense mutations
integrated_data_missense_only <- integrated_data %>%
  filter(Mutation_Type == "M")

integrated_data_missense_only <- integrated_data_missense_only %>%
  left_join(
    gnomAD_missense %>% select(Protein.Consequence.Short, Allele.Frequency),
    by = c("Substitution" = "Protein.Consequence.Short")
  )

# Define positive and negative cases
clinvar_pos <- c('Pathogenic/Likely pathogenic', 'Pathogenic', 'Likely pathogenic')
clinvar_neg <- c('Benign', 'Likely benign', 'Benign/Likely benign')
condition <- c('Hereditary cancer-predisposing syndrome|not provided')

# Create response variable with hierarchy:
# 1. Pathogenic cancer variants = 1 (highest priority)
# 2. Benign ClinVar variants = 0
# 3. gnomAD variants (not already classified) = 0
integrated_data_missense_only <- integrated_data_missense_only %>%
  mutate(response = case_when(
    # Positive cases: pathogenic cancer variants (checked first)
    `Germline classification` %in% clinvar_pos & `Condition(s)` %in% condition ~ 1,
    # Negative controls: benign ClinVar variants
    `Germline classification` %in% clinvar_neg ~ 0,
    # Additional negative controls: gnomAD variants
    !is.na(Allele.Frequency) ~ 0,
    # Everything else excluded
    TRUE ~ NA_real_
  ))

# Filter to only variants with defined response
roc_data <- integrated_data_missense_only %>%
  filter(!is.na(response))

# Check class distribution
cat("Class distribution:\n")
print(table(roc_data$response))
cat("\nPositives:", sum(roc_data$response == 1), 
    "\nNegatives:", sum(roc_data$response == 0), "\n")

# Break down the negative class
negatives_breakdown <- roc_data %>%
  filter(response == 0) %>%
  summarise(
    benign_clinvar = sum(`Germline classification` %in% clinvar_neg, na.rm = TRUE),
    gnomad_only = sum(!(`Germline classification` %in% clinvar_neg) & !is.na(Allele.Frequency), na.rm = TRUE)
  )
cat("\nNegative class breakdown:\n")
cat("  Benign ClinVar:", negatives_breakdown$benign_clinvar, "\n")
cat("  gnomAD only:", negatives_breakdown$gnomad_only, "\n")

# Create ROC curves
roc_cadd <- roc(roc_data$response, roc_data$PHRED)
roc_revel <- roc(roc_data$response, roc_data$REVEL)
roc_zscore <- roc(roc_data$response, roc_data$all_reps_zscore)
roc_am <- roc(roc_data$response, roc_data$am_pathogenicity)

# Plot
tiff("./plots/ROC_curves/ROC_missense_cancer_vs_benign_gnomad.tiff", 
     units="in", width=6, height=6, res=600)
plot(roc_zscore, col = "red", lwd=4, xlab = "Specificity", ylab = "Sensitivity",
     cex.lab=2, cex.axis=1.5)
plot(roc_cadd, col = "lightblue", lwd=4, add = TRUE)
plot(roc_revel, col = "gainsboro", lwd=4, add = TRUE)
plot(roc_am, col = "black", lwd=4, add = TRUE)

legend_text <- c(paste0("DMS (AUC=", round(auc(roc_zscore), 2), ")"),
                 paste0("CADD (AUC=", round(auc(roc_cadd), 2), ")"),
                 paste0("REVEL (AUC=", round(auc(roc_revel), 2), ")"),
                 paste0("AlphaMissense (AUC=", round(auc(roc_am), 2), ")"))
legend("bottomright", legend = legend_text, 
       col = c("red", "lightblue", "gainsboro", "black"), lwd = 4, cex=1.25)
dev.off()

# Save supplementary data
ROC_supp_data <- roc_data[,c(1,3,4,5,17,18,19,20,21,12,22)]
write_tsv(ROC_supp_data, "./results/ROC_curve_analysis/ROC_supp_data_benign_gnomad.tsv")


```


